name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - '[0-9]+.[0-9]{2}'
    tags:
      - 'v*'
  pull_request:

jobs:
  pkg:
    runs-on: ubuntu-20.04
    env:
      RELEASE_OUT: ./build
    strategy:
      fail-fast: false
      matrix:
        target:
          - debian-bullseye
          - debian-buster
          - raspbian-bullseye
          - raspbian-buster
          - ubuntu-bionic
          - ubuntu-focal
          - ubuntu-hirsute
          - ubuntu-impish
          - ubuntu-jammy
        platform:
          - linux/amd64
          - linux/arm
          - linux/arm64
        exclude:
          - target: raspbian-bullseye
            platform: linux/amd64
          - target: raspbian-bullseye
            platform: linux/arm64
          - target: raspbian-buster
            platform: linux/amd64
          - target: raspbian-buster
            platform: linux/arm64
    steps:
      -
        name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/bake-action@v1
        with:
          targets: ${{ matrix.target }}
          set: |
            *.platform=${{ matrix.platform }}
            *.cache-from=type=gha,scope=${{ matrix.target }}-${{ env.PLATFORM_PAIR }}
            *.cache-to=type=gha,scope=${{ matrix.target }}-${{ env.PLATFORM_PAIR }},mode=max
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}-${{ env.PLATFORM_PAIR }}
          path: ${{ env.RELEASE_OUT }}
          if-no-files-found: error
